// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: haqq/coinomics/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the inflation module's genesis state.
type GenesisState struct {
	// params defines all the paramaters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// current inflation rate
	Inflation github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=inflation,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"inflation"`
	// current era number
	Era uint64 `protobuf:"varint,3,opt,name=era,proto3" json:"era,omitempty"`
	// era started block number
	EraStartedAtBlock uint64 `protobuf:"varint,4,opt,name=era_started_at_block,json=eraStartedAtBlock,proto3" json:"era_started_at_block,omitempty"`
	// target mint for current era
	EraTargetMint github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=era_target_mint,json=eraTargetMint,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"era_target_mint" yaml:"era_target_mint"`
	// target supply for current era
	EraTargetSupply github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,6,opt,name=era_target_supply,json=eraTargetSupply,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"era_target_supply" yaml:"era_target_supply"`
	// total target supply
	TargetTotalSupply github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,7,opt,name=target_total_supply,json=targetTotalSupply,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"target_total_supply" yaml:"target_total_supply"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_228a4e7fa0b804ae, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetEra() uint64 {
	if m != nil {
		return m.Era
	}
	return 0
}

func (m *GenesisState) GetEraStartedAtBlock() uint64 {
	if m != nil {
		return m.EraStartedAtBlock
	}
	return 0
}

// Params holds parameters for the coinomics module.
type Params struct {
	// type of coin to mint
	MintDenom string `protobuf:"bytes,1,opt,name=mint_denom,json=mintDenom,proto3" json:"mint_denom,omitempty"`
	// number of blocks per era
	BlocksPerEra uint64 `protobuf:"varint,2,opt,name=blocks_per_era,json=blocksPerEra,proto3" json:"blocks_per_era,omitempty"`
	// parameter to enable coinmoics
	EnableCoinomics bool `protobuf:"varint,3,opt,name=enable_coinomics,json=enableCoinomics,proto3" json:"enable_coinomics,omitempty"`
	// Mint distribution of the minted denom
	MintDistribution MintDistribution `protobuf:"bytes,4,opt,name=mint_distribution,json=mintDistribution,proto3" json:"mint_distribution"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_228a4e7fa0b804ae, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMintDenom() string {
	if m != nil {
		return m.MintDenom
	}
	return ""
}

func (m *Params) GetBlocksPerEra() uint64 {
	if m != nil {
		return m.BlocksPerEra
	}
	return 0
}

func (m *Params) GetEnableCoinomics() bool {
	if m != nil {
		return m.EnableCoinomics
	}
	return false
}

func (m *Params) GetMintDistribution() MintDistribution {
	if m != nil {
		return m.MintDistribution
	}
	return MintDistribution{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "haqq.coinomics.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "haqq.coinomics.v1.Params")
}

func init() { proto.RegisterFile("haqq/coinomics/v1/genesis.proto", fileDescriptor_228a4e7fa0b804ae) }

var fileDescriptor_228a4e7fa0b804ae = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x6d, 0xb6, 0xae, 0x50, 0x33, 0x68, 0x6b, 0x26, 0x14, 0x2a, 0x91, 0x96, 0x80, 0xa0, 0x1c,
	0xe6, 0xa8, 0x70, 0x40, 0xe2, 0x46, 0x57, 0x04, 0x08, 0x26, 0x4d, 0xe9, 0xc4, 0x81, 0x4b, 0xe4,
	0xa4, 0xa6, 0xb3, 0x9a, 0xc4, 0x99, 0xed, 0x16, 0xfa, 0x1f, 0x38, 0x20, 0x2e, 0xf0, 0x93, 0x76,
	0xec, 0x11, 0x71, 0xa8, 0x50, 0xfb, 0x0f, 0xf8, 0x05, 0xc8, 0x76, 0xd6, 0x55, 0xeb, 0xa4, 0xb1,
	0x53, 0x9c, 0xf7, 0x3d, 0x7f, 0xef, 0xe5, 0xcb, 0xfb, 0x40, 0xe3, 0x08, 0x1f, 0x1f, 0x7b, 0x11,
	0xa3, 0x29, 0x4b, 0x68, 0x24, 0xbc, 0x71, 0xdb, 0x1b, 0x90, 0x94, 0x08, 0x2a, 0x50, 0xc6, 0x99,
	0x64, 0xb0, 0xa6, 0x08, 0x68, 0x49, 0x40, 0xe3, 0x76, 0x7d, 0x67, 0xc0, 0x06, 0x4c, 0x57, 0x3d,
	0x75, 0x32, 0xc4, 0xba, 0x13, 0x31, 0x91, 0x30, 0xe1, 0x85, 0x58, 0x10, 0x6f, 0xdc, 0x0e, 0x89,
	0xc4, 0x6d, 0xdd, 0x38, 0xaf, 0xdf, 0x5f, 0x57, 0x3a, 0xeb, 0xaa, 0x29, 0xee, 0x8f, 0x2d, 0xb0,
	0xfd, 0xda, 0xa8, 0xf7, 0x24, 0x96, 0x04, 0x3e, 0x07, 0xa5, 0x0c, 0x73, 0x9c, 0x08, 0xdb, 0x6a,
	0x5a, 0xad, 0x1b, 0x4f, 0xef, 0xa2, 0x35, 0x37, 0xe8, 0x40, 0x13, 0x3a, 0xc5, 0x93, 0x59, 0xa3,
	0xe0, 0xe7, 0x74, 0xf8, 0x1e, 0x94, 0x69, 0xfa, 0x29, 0xc6, 0x92, 0xb2, 0xd4, 0xde, 0x68, 0x5a,
	0xad, 0x72, 0x07, 0x29, 0xc2, 0xef, 0x59, 0xe3, 0xd1, 0x80, 0xca, 0xa3, 0x51, 0x88, 0x22, 0x96,
	0x78, 0xb9, 0x65, 0xf3, 0xd8, 0x15, 0xfd, 0xa1, 0x27, 0x27, 0x19, 0x11, 0xa8, 0x4b, 0x22, 0xff,
	0xac, 0x01, 0xac, 0x82, 0x4d, 0xc2, 0xb1, 0xbd, 0xd9, 0xb4, 0x5a, 0x45, 0x5f, 0x1d, 0xa1, 0x07,
	0x76, 0x08, 0xc7, 0x81, 0x90, 0x98, 0x4b, 0xd2, 0x0f, 0xb0, 0x0c, 0xc2, 0x98, 0x45, 0x43, 0xbb,
	0xa8, 0x29, 0x35, 0xc2, 0x71, 0xcf, 0x94, 0x5e, 0xca, 0x8e, 0x2a, 0xc0, 0xaf, 0x16, 0xa8, 0xa8,
	0x1b, 0x12, 0xf3, 0x01, 0x91, 0x41, 0x42, 0x53, 0x69, 0x6f, 0xe5, 0xdf, 0x64, 0xe4, 0x91, 0x1a,
	0x1c, 0xca, 0x07, 0x87, 0xf6, 0x18, 0x4d, 0x3b, 0x6f, 0x73, 0xcb, 0x8f, 0xff, 0xc3, 0xb2, 0xba,
	0xf0, 0x77, 0xd6, 0xb8, 0x33, 0xc1, 0x49, 0xfc, 0xc2, 0x3d, 0x27, 0xe5, 0xfa, 0x37, 0x09, 0xc7,
	0x87, 0x1a, 0xd8, 0xa7, 0xa9, 0x84, 0xdf, 0x2d, 0x50, 0x5b, 0xe1, 0x88, 0x51, 0x96, 0xc5, 0x13,
	0xbb, 0x74, 0x99, 0xa1, 0x77, 0x57, 0x37, 0x64, 0xaf, 0x19, 0x32, 0x62, 0xae, 0x5f, 0x59, 0x5a,
	0xea, 0x69, 0x04, 0xfe, 0xb4, 0xc0, 0xed, 0x9c, 0x23, 0x99, 0xc4, 0xf1, 0xa9, 0xad, 0x6b, 0x97,
	0xd9, 0xda, 0xbf, 0xba, 0xad, 0xba, 0xb1, 0x75, 0x81, 0x9c, 0xeb, 0xd7, 0x0c, 0x7a, 0xa8, 0x40,
	0x63, 0xcd, 0x9d, 0x5a, 0xa0, 0x64, 0x82, 0x06, 0xef, 0x01, 0xa0, 0x46, 0x1a, 0xf4, 0x49, 0xca,
	0x12, 0x9d, 0xcb, 0xb2, 0x5f, 0x56, 0x48, 0x57, 0x01, 0xf0, 0x21, 0xb8, 0xa5, 0xa3, 0x20, 0x82,
	0x8c, 0xf0, 0x40, 0xc5, 0x66, 0x43, 0x67, 0x62, 0xdb, 0xa0, 0x07, 0x84, 0xbf, 0xe2, 0x18, 0x3e,
	0x01, 0x55, 0x92, 0xe2, 0x30, 0x26, 0xc1, 0x32, 0xcb, 0x3a, 0x5e, 0xd7, 0xfd, 0x8a, 0xc1, 0xf7,
	0x4e, 0x61, 0xf8, 0x01, 0xd4, 0x8c, 0x1e, 0x15, 0x92, 0xd3, 0x70, 0xa4, 0x23, 0x5d, 0xd4, 0x23,
	0x79, 0x70, 0xc1, 0x3a, 0xa8, 0xdf, 0xdb, 0x5d, 0xa1, 0xe6, 0x8b, 0x51, 0x4d, 0xce, 0xe3, 0x6f,
	0x4e, 0xe6, 0x8e, 0x35, 0x9d, 0x3b, 0xd6, 0x9f, 0xb9, 0x63, 0x7d, 0x5b, 0x38, 0x85, 0xe9, 0xc2,
	0x29, 0xfc, 0x5a, 0x38, 0x85, 0x8f, 0x68, 0x65, 0x8c, 0x4a, 0x60, 0x37, 0x25, 0xf2, 0x33, 0xe3,
	0x43, 0xfd, 0xe2, 0x7d, 0x59, 0xd9, 0x61, 0x3d, 0xd2, 0xb0, 0xa4, 0xb7, 0xf7, 0xd9, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x10, 0x7c, 0x83, 0xe6, 0x4c, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TargetTotalSupply.Size()
		i -= size
		if _, err := m.TargetTotalSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.EraTargetSupply.Size()
		i -= size
		if _, err := m.EraTargetSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.EraTargetMint.Size()
		i -= size
		if _, err := m.EraTargetMint.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.EraStartedAtBlock != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.EraStartedAtBlock))
		i--
		dAtA[i] = 0x20
	}
	if m.Era != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Era))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.Inflation.Size()
		i -= size
		if _, err := m.Inflation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MintDistribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.EnableCoinomics {
		i--
		if m.EnableCoinomics {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.BlocksPerEra != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BlocksPerEra))
		i--
		dAtA[i] = 0x10
	}
	if len(m.MintDenom) > 0 {
		i -= len(m.MintDenom)
		copy(dAtA[i:], m.MintDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MintDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.Inflation.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Era != 0 {
		n += 1 + sovGenesis(uint64(m.Era))
	}
	if m.EraStartedAtBlock != 0 {
		n += 1 + sovGenesis(uint64(m.EraStartedAtBlock))
	}
	l = m.EraTargetMint.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.EraTargetSupply.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TargetTotalSupply.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MintDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.BlocksPerEra != 0 {
		n += 1 + sovGenesis(uint64(m.BlocksPerEra))
	}
	if m.EnableCoinomics {
		n += 2
	}
	l = m.MintDistribution.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inflation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Inflation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Era", wireType)
			}
			m.Era = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Era |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EraStartedAtBlock", wireType)
			}
			m.EraStartedAtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EraStartedAtBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EraTargetMint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EraTargetMint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EraTargetSupply", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EraTargetSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetTotalSupply", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetTotalSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksPerEra", wireType)
			}
			m.BlocksPerEra = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksPerEra |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableCoinomics", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableCoinomics = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDistribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintDistribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
